"""PDF report generation utility.

Renders Markdown (typically an analyst answer) into a corporate-styled PDF.
The Markdown is converted to HTML and laid out with ``fpdf2`` — a pure-Python
engine, so there are no system-level rendering dependencies.
"""

from __future__ import annotations

import logging
from pathlib import Path

import markdown as md
from fpdf import FPDF

from backend.core.config import get_settings

logger = logging.getLogger(__name__)

# fpdf2's core fonts are Latin-1 only. Map the non-Latin-1 characters that
# routinely appear in Infosys financials to safe equivalents; anything else is
# replaced during the final encode pass.
_CHAR_REPLACEMENTS = {
    "₹": "Rs.",   # ₹ rupee sign
    "–": "-",      # – en dash
    "—": "-",      # — em dash
    "‘": "'", "’": "'",   # ' ' smart single quotes
    "“": '"', "”": '"',   # " " smart double quotes
    "•": "-",      # • bullet
    "…": "...",   # … ellipsis
    " ": " ",      # non-breaking space
}

_TITLE = "Infosys Financial Analyst Report"
_BRAND_NAVY = (0, 51, 102)


def _to_latin1(text: str) -> str:
    """Make text safe for fpdf2's core fonts (Latin-1 only)."""
    for unicode_char, replacement in _CHAR_REPLACEMENTS.items():
        text = text.replace(unicode_char, replacement)
    return text.encode("latin-1", "replace").decode("latin-1")


class _ReportPDF(FPDF):
    """FPDF subclass that paints a corporate header band and page footer."""

    def header(self) -> None:  # noqa: D102 - fpdf2 lifecycle hook
        self.set_fill_color(*_BRAND_NAVY)
        self.rect(0, 0, self.w, 20, style="F")
        self.set_xy(self.l_margin, 5)
        self.set_font("Helvetica", "B", 15)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, _TITLE)
        self.set_y(28)
        self.set_text_color(0, 0, 0)

    def footer(self) -> None:  # noqa: D102 - fpdf2 lifecycle hook
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Page {self.page_no()}  -  Generated by LedgerMind", align="C")


def generate_pdf_report(markdown_text: str, filename: str = "report.pdf") -> str:
    """Render ``markdown_text`` into a styled PDF and return its absolute path.

    Args:
        markdown_text: The report body in Markdown (headings, tables, lists).
        filename: Output file name; ``.pdf`` is appended if missing.

    Returns:
        The absolute path to the written PDF.
    """
    exports_dir = get_settings().EXPORTS_DIR
    exports_dir.mkdir(parents=True, exist_ok=True)

    if not filename.lower().endswith(".pdf"):
        filename = f"{filename}.pdf"
    output_path = exports_dir / Path(filename).name

    # Markdown -> HTML (tables + code fences), then sanitise for the core fonts.
    html = md.markdown(
        _to_latin1(markdown_text),
        extensions=["tables", "fenced_code", "sane_lists"],
    )

    pdf = _ReportPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()
    pdf.set_font("Helvetica", size=11)
    pdf.write_html(html)
    pdf.output(str(output_path))

    absolute = str(output_path.resolve())
    logger.info("PDF report written: %s.", absolute)
    return absolute
