"""PDF report generation utility.

Renders a Markdown analyst answer into a corporate-styled PDF with ``fpdf2``.

The document uses the bundled **DejaVu Sans** Unicode font, so financial
symbols — the ₹ rupee sign, en/em dashes, smart quotes, bullets — render
correctly instead of being stripped or mangled. Markdown is rendered directly
(headings, paragraphs, bullet lists, tables) for full control over the font.
"""

from __future__ import annotations

import logging
from pathlib import Path

from fpdf import FPDF

from backend.core.config import get_settings

logger = logging.getLogger(__name__)

_FONT_DIR = Path(__file__).parent / "fonts"
_FONT_REGULAR = _FONT_DIR / "DejaVuSans.ttf"
_FONT_BOLD = _FONT_DIR / "DejaVuSans-Bold.ttf"
_FONT_FAMILY = "DejaVu"

_TITLE = "Infosys Financial Analyst Report"
_BRAND_NAVY = (0, 51, 102)
_HEADING_SIZES = {1: 15, 2: 13, 3: 12}
_BODY_SIZE = 11


class _ReportPDF(FPDF):
    """FPDF subclass that paints a corporate header band and page footer."""

    def header(self) -> None:  # noqa: D102 - fpdf2 lifecycle hook
        self.set_fill_color(*_BRAND_NAVY)
        self.rect(0, 0, self.w, 20, style="F")
        self.set_xy(self.l_margin, 5)
        self.set_font(_FONT_FAMILY, "B", 15)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, _TITLE)
        self.set_y(28)
        self.set_text_color(0, 0, 0)

    def footer(self) -> None:  # noqa: D102 - fpdf2 lifecycle hook
        self.set_y(-15)
        self.set_font(_FONT_FAMILY, "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Page {self.page_no()}  -  Generated by LedgerMind", align="C")


def _register_fonts(pdf: FPDF) -> None:
    """Register DejaVu Sans for every style (no crash on italic requests)."""
    pdf.add_font(_FONT_FAMILY, "", str(_FONT_REGULAR))
    pdf.add_font(_FONT_FAMILY, "B", str(_FONT_BOLD))
    # No dedicated italic file is bundled — map italic styles onto the files we
    # have so the renderer never raises on an <em>/markdown italic request.
    pdf.add_font(_FONT_FAMILY, "I", str(_FONT_REGULAR))
    pdf.add_font(_FONT_FAMILY, "BI", str(_FONT_BOLD))


def _render_table(pdf: FPDF, table_lines: list[str]) -> None:
    """Render a Markdown table block using fpdf2's native table API."""
    rows: list[list[str]] = []
    for line in table_lines:
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        # Skip the |---|---| separator row.
        if all(set(cell) <= set("-: ") and cell for cell in cells):
            continue
        rows.append(cells)
    if not rows:
        return

    pdf.set_font(_FONT_FAMILY, "", 9)
    with pdf.table(markdown=True, first_row_as_headings=True) as table:
        for row in rows:
            table.row(row)
    pdf.set_font(_FONT_FAMILY, "", _BODY_SIZE)
    pdf.ln(2)


def _render_markdown(pdf: FPDF, markdown_text: str) -> None:
    """Render Markdown to the PDF block by block (headings, lists, tables)."""
    lines = markdown_text.split("\n")
    index = 0
    while index < len(lines):
        stripped = lines[index].strip()

        if not stripped:
            pdf.ln(2)
            index += 1
            continue

        # --- Table block (consecutive pipe rows) ---------------------------- #
        if stripped.startswith("|") and stripped.endswith("|"):
            block: list[str] = []
            while index < len(lines) and lines[index].strip().startswith("|"):
                block.append(lines[index])
                index += 1
            _render_table(pdf, block)
            continue

        # --- Heading -------------------------------------------------------- #
        if stripped.startswith("#"):
            level = len(stripped) - len(stripped.lstrip("#"))
            heading = stripped.lstrip("#").strip()
            pdf.set_font(_FONT_FAMILY, "B", _HEADING_SIZES.get(level, _BODY_SIZE))
            pdf.multi_cell(0, 7, heading)
            pdf.set_font(_FONT_FAMILY, "", _BODY_SIZE)
            pdf.ln(1)
            index += 1
            continue

        # --- Horizontal rule ------------------------------------------------ #
        if set(stripped) <= {"-", "*", "_"} and len(stripped) >= 3:
            pdf.ln(2)
            index += 1
            continue

        # --- Bullet list item ---------------------------------------------- #
        if stripped.startswith(("- ", "* ", "+ ")):
            pdf.set_font(_FONT_FAMILY, "", _BODY_SIZE)
            # Extract bullet text, sanitizing problematic characters
            bullet_text = stripped[2:].strip()
            # Normalize unicode dashes that fpdf2 may struggle with
            bullet_text = bullet_text.replace('–', '-').replace('—', '-')
            # Remove markdown formatting that might cause width calculation issues
            bullet_text = bullet_text.replace('**', '').replace('*', '').replace('_', '')
            # Truncate if line is extremely long
            if len(bullet_text) > 220:
                bullet_text = bullet_text[:217] + "..."
            
            try:
                # Use a specific width to avoid fpdf2 width calculation issues
                # Width of 165 should work for A4 with margins
                pdf.multi_cell(165, 6, f"- {bullet_text}", markdown=False)
            except Exception as e:  # noqa: BLE001
                logger.debug("Bullet rendering failed: %s", e)
                try:
                    # Fallback: render as plain text without special formatting
                    pdf.multi_cell(0, 6, f"- {bullet_text}")
                except Exception as ex:
                    # Last resort: just skip if it fails
                    logger.debug("Bullet rendering fallback also failed: %s", ex)
            pdf.ln(1)
            index += 1
            continue

        # --- Block quote (used for the unverified-answer warning) ---------- #
        if stripped.startswith(">"):
            pdf.set_font(_FONT_FAMILY, "I", 10)
            pdf.multi_cell(0, 6, stripped.lstrip(">").strip(), markdown=True)
            pdf.set_font(_FONT_FAMILY, "", _BODY_SIZE)
            pdf.ln(1)
            index += 1
            continue

        # --- Plain paragraph ------------------------------------------------ #
        pdf.set_font(_FONT_FAMILY, "", _BODY_SIZE)
        pdf.multi_cell(0, 6, stripped, markdown=True)
        pdf.ln(1)
        index += 1


def generate_pdf_report(markdown_text: str, filename: str = "report.pdf") -> str:
    """Render ``markdown_text`` into a styled PDF and return its absolute path.

    Args:
        markdown_text: The report body in Markdown (headings, tables, lists).
        filename: Output file name; ``.pdf`` is appended if missing.

    Returns:
        The absolute path to the written PDF.
    """
    exports_dir = get_settings().EXPORTS_DIR
    exports_dir.mkdir(parents=True, exist_ok=True)

    if not filename.lower().endswith(".pdf"):
        filename = f"{filename}.pdf"
    output_path = exports_dir / Path(filename).name

    pdf = _ReportPDF()
    _register_fonts(pdf)
    # Reduce margin from 20 to 15 to give more horizontal space for multi_cell
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font(_FONT_FAMILY, "", _BODY_SIZE)
    _render_markdown(pdf, markdown_text)
    pdf.output(str(output_path))

    absolute = str(output_path.resolve())
    logger.info("PDF report written: %s.", absolute)
    return absolute
